name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ./src/Ozbul.Application.Portal.sln

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore Dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build --configuration Release --no-restore ${{ env.SOLUTION_PATH }}

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal ${{ env.SOLUTION_PATH }}
